import type { Metadata } from "next";
import { Nunito, Oswald } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="color-scheme"
          content="dark light"
        />
      </head>
      <body className={`${nunito.variable} ${oswald.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
